-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 15:59:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbe_commerce : base de données
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbe_commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbe_commerce` DEFAULT CHARACTER SET utf8 ;
USE `dbe_commerce` ;

-- -----------------------------------------------------
-- Table `dbe_commerce`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbe_commerce`.`admins` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `pass` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbe_commerce`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbe_commerce`.`utilisateurs` (
  `id` INT(100) NOT NULL,
  `nom` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `pass` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbe_commerce`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbe_commerce`.`produits` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `details` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `prix` INT(10) NOT NULL,
  `image_01` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `image_02` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `image_03` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbe_commerce`.`chariot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbe_commerce`.`chariot` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `prix` INT(10) NOT NULL,
  `quantite` INT(10) NOT NULL,
  `image` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `utilisateurs_id` INT(100) NOT NULL,
  `produits_id` INT(100) NOT NULL,
  PRIMARY KEY (`id`, `utilisateurs_id`, `produits_id`),
  INDEX `fk_chariot_utilisateurs1_idx` (`utilisateurs_id` ASC),
  INDEX `fk_chariot_produits1_idx` (`produits_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbe_commerce`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbe_commerce`.`messages` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `numero` VARCHAR(12) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `message` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `utilisateurs_id` INT(100) NOT NULL,
  PRIMARY KEY (`id`, `utilisateurs_id`),
  INDEX `fk_messages_utilisateurs1_idx` (`utilisateurs_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbe_commerce`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbe_commerce`.`commandes` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `numero` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `methode` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `adresse` VARCHAR(500) NOT NULL,
  `produits_total` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `prix_total` INT(100) NOT NULL,
  `place_sur` DATE NOT NULL DEFAULT current_timestamp(),
  `statut_paiement` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL DEFAULT 'en attente',
  `utilisateurs_id` INT(100) NOT NULL,
  PRIMARY KEY (`id`, `utilisateurs_id`),
  INDEX `fk_commandes_utilisateurs1_idx` (`utilisateurs_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbe_commerce`.`liste_souhaits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbe_commerce`.`liste_souhaits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `prix` INT(100) NOT NULL,
  `image` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `utilisateurs_id` INT(100) NOT NULL,
  `produits_id` INT(100) NOT NULL,
  PRIMARY KEY (`id`, `utilisateurs_id`, `produits_id`),
  INDEX `fk_liste_souhaits_utilisateurs_idx` (`utilisateurs_id` ASC),
  INDEX `fk_liste_souhaits_produits1_idx` (`produits_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
